import pptxgen from 'pptxgenjs';
import fs from 'node:fs';
import path from 'node:path';
import { parseArgs, ensureDir, root } from './lib.mjs';
import { loadCanonicalLecture } from './lecture-contract.mjs';

const args = parseArgs(process.argv);
if (!args.input || !args.output) throw new Error('Use --input <lecture.json> --output <deck.pptx>');
const input = path.resolve(args.input), output = path.resolve(args.output);
const data = loadCanonicalLecture(input);
const design = JSON.parse(fs.readFileSync(path.join(root, 'config/design-system.json'), 'utf8'));
const subject = JSON.parse(fs.readFileSync(path.join(root, `config/subjects/${data.metadata.subject}.json`), 'utf8'));
const pptx = new pptxgen();
pptx.layout = design.ratio;
pptx.author = 'Unique Group of Institutions';
pptx.subject = data.metadata.unit;
pptx.title = data.metadata.title;
pptx.lang = 'en-US';
pptx.theme = { headFontFace: design.fonts.display, bodyFontFace: design.fonts.body, lang: 'en-US' };
const C = design.colors, accent = subject.accent;
const W = 13.333, H = 7.5;
function addChrome(slide,index){slide.background={color:C.paper};slide.addShape(pptx.ShapeType.line,{x:.55,y:.76,w:12.2,h:0,line:{color:C.line,width:1}});slide.addText(`${subject.label.toUpperCase()}  •  CLASS ${data.metadata.class}  •  LECTURE ${String(data.metadata.lecture).padStart(2,'0')}`,{x:.58,y:.19,w:7.8,h:.3,fontFace:design.fonts.body,fontSize:11,bold:true,color:C.blue,margin:0});slide.addText(String(index).padStart(2,'0'),{x:12.05,y:7.12,w:.65,h:.2,fontSize:10,color:C.muted,align:'right',margin:0});slide.addText('Unique Group of Institutions',{x:.58,y:7.10,w:3.2,h:.22,fontSize:9,color:C.muted,margin:0});}
function title(slide,text){slide.addText(text,{x:.58,y:.92,w:12.1,h:.58,fontFace:design.fonts.display,fontSize:design.sizes.slideTitle,bold:true,color:C.navy,margin:0,fit:'shrink'});}
function addNotes(slide,item){const refs=(item?.sources||[]).map(s=>`Page ${s.pageNumber}, offsets ${s.startOffset}-${s.endOffset}: ${s.text}`);const narration=item?.narration?`\n[Narration]\n${item.narration}`:'';slide.addNotes(`[Sources]\n${refs.join('\n')||`Textbook pages: ${data.metadata.textbookPages}; LMS scope: ${data.metadata.lmsScope}`}${narration}`);}
function bullets(slide,items,x=.8,y=2,w=11.5,h=4.3,size=22){slide.addText(items.map((t,i)=>({text:t,options:{bullet:{indent:18},breakLine:i<items.length-1}})),{x,y,w,h,fontSize:size,color:C.ink,breakLine:false,paraSpaceAfterPt:12,margin:.05,fit:'shrink',valign:'mid'});}
function panel(slide,x,y,w,h,heading,items,color=accent){slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:.06,fill:{color:'FFFFFF'},line:{color,width:2}});slide.addText(heading,{x:x+.25,y:y+.22,w:w-.5,h:.4,fontSize:23,bold:true,color,margin:0,fit:'shrink'});bullets(slide,items,x+.28,y+.85,w-.56,h-.98,18);}
function renderConcept(s,i){if(i.lead)s.addText(i.lead,{x:.78,y:1.65,w:11.6,h:1.05,fontSize:25,bold:true,color:C.ink,margin:.02,fit:'shrink'});bullets(s,i.bullets,.9,i.lead?2.85:1.75,10.9,i.lead?3.5:4.5,21);}
function renderComparison(s,i){const cols=i.columns.slice(0,3),gap=.25,margin=.65,w=(12.03-gap*(cols.length-1))/cols.length;cols.forEach((c,n)=>panel(s,margin+n*(w+gap),1.72,w,4.95,c.title,c.items,n===0?accent:C.gold));}
function renderProcess(s,i){const steps=i.steps,gap=.22,x0=.7,y=2,w=(11.95-gap*(steps.length-1))/steps.length;steps.forEach((step,n)=>{const x=x0+n*(w+gap);s.addShape(pptx.ShapeType.roundRect,{x,y,w,h:3.85,rectRadius:.05,fill:{color:n%2?'F7F8FA':'EEF4FA'},line:{color:n%2?C.gold:accent,width:2}});s.addShape(pptx.ShapeType.ellipse,{x:x+w/2-.3,y:y+.35,w:.6,h:.6,fill:{color:n%2?C.gold:accent},line:{color:n%2?C.gold:accent}});s.addText(String(n+1),{x:x+w/2-.25,y:y+.48,w:.5,h:.2,fontSize:13,bold:true,color:C.white,align:'center',margin:0});s.addText(step,{x:x+.22,y:y+1.25,w:w-.44,h:2.15,fontSize:17,bold:true,color:C.ink,align:'center',valign:'mid',margin:.05,fit:'shrink'});if(n<steps.length-1)s.addText('→',{x:x+w-.02,y:y+1.65,w:.32,h:.4,fontSize:24,bold:true,color:C.muted,margin:0});});}
function renderFormula(s,i){s.addShape(pptx.ShapeType.roundRect,{x:.8,y:1.75,w:11.7,h:1.75,rectRadius:.06,fill:{color:'EEF4FA'},line:{color:accent,width:2}});s.addText(i.formula,{x:1.05,y:2.12,w:11.2,h:.95,fontFace:design.fonts.display,fontSize:34,bold:true,color:C.navy,align:'center',valign:'mid',margin:.02,fit:'shrink'});if(i.variables?.length)panel(s,1.05,3.85,11.15,2.25,'Where:',i.variables,accent);}
function renderWorkedExample(s,i){s.addText(i.problem,{x:.8,y:1.62,w:11.7,h:.75,fontSize:21,bold:true,color:C.ink,margin:.02,fit:'shrink'});const rows=[['Given',i.given?.join(' • ')],['Formula',i.formula],['Substitution',i.substitution],['Calculation',i.calculation],['Answer',i.answer]];rows.forEach((r,n)=>{const y=2.45+n*.78;s.addText(r[0],{x:.85,y,w:1.45,h:.35,fontSize:15,bold:true,color:n===4?accent:C.blue,margin:0});s.addText(r[1],{x:2.35,y,w:9.9,h:.48,fontSize:n===4?20:16,bold:n===4,color:n===4?C.navy:C.ink,margin:.02,fit:'shrink'});if(n<rows.length-1)s.addShape(pptx.ShapeType.line,{x:2.35,y:y+.58,w:9.7,h:0,line:{color:C.line,width:1}});});}
function renderVisual(s,i){const vt=i.visualType||'illustration';s.addShape(pptx.ShapeType.roundRect,{x:.85,y:1.65,w:7.35,h:4.75,rectRadius:.06,fill:{color:'EEF4FA'},line:{color:accent,width:2}});s.addText(vt.toUpperCase(),{x:1.15,y:2,w:6.75,h:.35,fontSize:14,bold:true,color:accent,align:'center',margin:0});if(i.labels?.length)i.labels.slice(0,6).forEach((label,n)=>{const a=Math.PI*2*n/Math.max(1,Math.min(6,i.labels.length)),cx=4.52+2.35*Math.cos(a),cy=4+1.35*Math.sin(a);s.addShape(pptx.ShapeType.ellipse,{x:cx-.55,y:cy-.28,w:1.1,h:.56,fill:{color:C.white},line:{color:C.gold,width:1.5}});s.addText(label,{x:cx-.48,y:cy-.12,w:.96,h:.22,fontSize:11,bold:true,color:C.navy,align:'center',margin:0,fit:'shrink'});});else{s.addShape(pptx.ShapeType.ellipse,{x:3.2,y:3,w:2.65,h:1.65,fill:{color:C.white},line:{color:accent,width:3}});s.addText(vt,{x:3.45,y:3.55,w:2.15,h:.3,fontSize:19,bold:true,color:C.navy,align:'center',margin:0});}s.addText(i.caption,{x:8.55,y:2.05,w:3.75,h:3.85,fontSize:23,bold:true,color:C.ink,margin:.05,fit:'shrink',valign:'mid'});}
function renderQuickCheck(s,i){i.questions.forEach((q,n)=>{const y=1.75+n*1.05;s.addShape(pptx.ShapeType.ellipse,{x:.82,y:y+.02,w:.55,h:.55,fill:{color:accent},line:{color:accent}});s.addText(String(n+1),{x:.95,y:y+.18,w:.3,h:.18,fontSize:11,bold:true,color:C.white,align:'center',margin:0});s.addText(q,{x:1.55,y,w:10.8,h:.65,fontSize:21,bold:true,color:C.ink,margin:.02,fit:'shrink'});});s.addShape(pptx.ShapeType.roundRect,{x:1.2,y:5.2,w:10.8,h:.95,rectRadius:.05,fill:{color:'FFF7D6'},line:{color:C.gold,width:2}});s.addText(`Answer: ${i.answer}`,{x:1.45,y:5.47,w:10.3,h:.4,fontSize:18,bold:true,color:C.navy,align:'center',margin:.02,fit:'shrink'});}
function renderTeachingSlide(s,i){switch(i.type){case'concept':return renderConcept(s,i);case'comparison':return renderComparison(s,i);case'process':return renderProcess(s,i);case'formula':return renderFormula(s,i);case'worked-example':return renderWorkedExample(s,i);case'visual':return renderVisual(s,i);case'quick-check':return renderQuickCheck(s,i);default:throw new Error(`Unsupported slide type: ${i.type}`);}}
let n=1;{const s=pptx.addSlide();s.background={color:C.navy};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:W,h:.18,fill:{color:C.gold},line:{color:C.gold}});s.addText(`${subject.label.toUpperCase()} • CLASS ${data.metadata.class}`,{x:.72,y:.78,w:7,h:.35,fontSize:15,bold:true,color:C.gold,margin:0});s.addText(data.metadata.title,{x:.72,y:1.55,w:10.9,h:1.25,fontFace:design.fonts.display,fontSize:design.sizes.deckTitle,bold:true,color:C.white,margin:0,fit:'shrink'});s.addText(`Unit ${data.metadata.unit}\nLecture ${String(data.metadata.lecture).padStart(2,'0')}  |  ${data.metadata.lmsScope}`,{x:.76,y:3,w:8.5,h:.8,fontSize:20,color:'DCE5FF',margin:0});s.addShape(pptx.ShapeType.rect,{x:.75,y:5.55,w:4.1,h:.08,fill:{color:accent},line:{color:accent}});s.addText('TEXTBOOK-ALIGNED • LMS-ALIGNED • TEACHER-READY',{x:.75,y:5.8,w:7.5,h:.35,fontSize:12,bold:true,color:C.white,margin:0});addNotes(s);n++;}
{const s=pptx.addSlide();addChrome(s,n++);title(s,'Introduction');s.addText(data.introduction,{x:.78,y:1.85,w:7.2,h:3.9,fontSize:27,bold:true,color:C.ink,margin:.05,fit:'shrink',valign:'mid'});addNotes(s);}
{const s=pptx.addSlide();addChrome(s,n++);title(s,'Student Learning Objectives');s.addText('By the end of this lecture, students will be able to:',{x:.78,y:1.65,w:8.5,h:.4,fontSize:22,color:C.muted,margin:0});bullets(s,data.slos,.9,2.15,10.9,4.45,21);addNotes(s);}
if(data.previousKnowledge){const s=pptx.addSlide();addChrome(s,n++);title(s,'Let’s Connect');s.addText(data.previousKnowledge,{x:1,y:2.05,w:11.2,h:2.6,fontSize:30,bold:true,color:C.ink,align:'center',valign:'mid',margin:.1,fit:'shrink'});addNotes(s);}
for(const item of data.slides){const s=pptx.addSlide();addChrome(s,n++);title(s,item.title);renderTeachingSlide(s,item);addNotes(s,item);}
{const s=pptx.addSlide();addChrome(s,n++);title(s,'Lecture Recap');bullets(s,data.recap,.9,1.9,10.9,4.5,21);addNotes(s);}
{const s=pptx.addSlide();addChrome(s,n++);title(s,'Review Questions');bullets(s,data.reviewQuestions,.9,1.85,10.9,4.65,21);if(data.nextLectureBridge)s.addText(data.nextLectureBridge,{x:.78,y:6.3,w:11.65,h:.45,fontSize:15,italic:true,color:C.blue,margin:.05,fit:'shrink'});addNotes(s);}
ensureDir(output);await pptx.writeFile({fileName:output});console.log(`Created ${output}`);
