# Generated by Django 6.0.8 on 2026-08-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ugi_crm', max_length=50)),
                ('external_user_id', models.CharField(max_length=255, unique=True)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('local_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'external_user_id')},
            },
        ),
    ]
