# Generated by Django 6.0.8 on 2026-08-06 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='lectures.course')),
            ],
            options={
                'ordering': ('course', 'number'),
            },
        ),
        migrations.CreateModel(
            name='LectureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('learning_objectives', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_requests', to='lectures.chapter')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'is_active'], name='course_teacher_active_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['course', 'number'], name='chapter_course_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'number'), name='unique_chapter_number'),
        ),
        migrations.AddIndex(
            model_name='lecturerequest',
            index=models.Index(fields=['requested_by', 'status'], name='lecture_requester_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerequest',
            index=models.Index(fields=['chapter', 'status'], name='lecture_chapter_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturerequest',
            constraint=models.CheckConstraint(condition=models.Q(('learning_objectives', ''), _negated=True), name='lecture_objectives_not_empty'),
        ),
    ]
