# Generated by Django 6.0.8 on 2026-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='chapter_number_positive'),
        ),
    ]
