# Generated by Django 6.0.8 on 2026-08-06 13:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_chapter_chapter_number_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('INSTITUTIONAL', 'Institutional textbook or notes'), ('TEACHER', 'Teacher-owned upload')], max_length=20)),
                ('access_scope', models.CharField(choices=[('AUTHORIZED_TEACHERS', 'Authorized teachers'), ('OWNER_AND_ADMINS', 'Owner and administrators')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('rights_confirmed', models.BooleanField(default=False)),
                ('rights_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('processing_state', models.CharField(choices=[('REGISTERED', 'Registered'), ('READY', 'Ready'), ('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Teacher review required'), ('FAILED', 'Failed safely')], default='REGISTERED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_sources', to='lectures.chapter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_content_sources', to=settings.AUTH_USER_MODEL)),
                ('rights_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rights_confirmed_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('chapter', 'title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('extension', models.CharField(max_length=8)),
                ('media_type', models.CharField(max_length=40)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='original_file', to='lectures.contentsource')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('REVIEW_REQUIRED', 'Teacher review required'), ('FAILED', 'Failed safely')], default='PENDING', max_length=24)),
                ('extractor', models.CharField(max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='lectures.contentsource')),
            ],
            options={
                'ordering': ('source', 'version'),
            },
        ),
        migrations.CreateModel(
            name='ExtractedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('PDF_TEXT', 'PDF text layer'), ('OCR', 'Local OCR')], max_length=16)),
                ('text_storage_key', models.CharField(max_length=255)),
                ('text_sha256', models.CharField(max_length=64)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('mean_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_pages', to='lectures.contentfile')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='lectures.extractionversion')),
            ],
            options={
                'ordering': ('extraction', 'page_number'),
            },
        ),
        migrations.AddIndex(
            model_name='contentsource',
            index=models.Index(fields=['chapter', 'source_type'], name='content_chapter_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsource',
            index=models.Index(fields=['owner', 'processing_state'], name='content_owner_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('source_type', 'INSTITUTIONAL')), models.Q(('owner__isnull', False), ('source_type', 'TEACHER')), _connector='OR'), name='content_source_owner_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='contentsource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_scope', 'AUTHORIZED_TEACHERS'), ('source_type', 'INSTITUTIONAL')), models.Q(('access_scope', 'OWNER_AND_ADMINS'), ('source_type', 'TEACHER')), _connector='OR'), name='content_source_scope_matches_type'),
        ),
        migrations.AddIndex(
            model_name='contentfile',
            index=models.Index(fields=['sha256'], name='content_file_sha_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionversion',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='unique_source_extraction_version'),
        ),
        migrations.AddIndex(
            model_name='extractedpage',
            index=models.Index(fields=['source_file', 'page_number'], name='content_file_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractedpage',
            constraint=models.UniqueConstraint(fields=('extraction', 'page_number'), name='unique_extraction_page'),
        ),
    ]
