# Generated by Django 6.0.8 on 2026-08-07 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_course_class_name_course_subject_name_contentsource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='extractedpage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'PDF_TEXT'), ('requires_review', False), ('review_status', 'NOT_REQUIRED'), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('method', 'OCR'), ('requires_review', True), ('review_status', 'PENDING'), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True)), models.Q(('method', 'OCR'), ('requires_review', False), ('review_status', 'APPROVED'), ('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='extracted_page_review_invariants'),
        ),
    ]
