# Generated by Django 6.0.8 on 2026-08-11 07:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_extractedpage_extracted_page_review_invariants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guidelines', models.JSONField()),
                ('generator_key', models.CharField(max_length=64)),
                ('input_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated draft'), ('PARTIALLY_APPROVED', 'Partially approved'), ('APPROVED', 'Teacher approved')], default='GENERATED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_requests', to='lectures.chapter')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='GenerationSourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_sha256', models.CharField(max_length=64)),
                ('extraction_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('source_title', models.CharField(max_length=200)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_snapshots', to='lectures.extractionversion')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_snapshots', to='lectures.generationrequest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_snapshots', to='lectures.contentsource')),
            ],
            options={
                'ordering': ('generation', 'source_id'),
            },
        ),
        migrations.CreateModel(
            name='GenerationPageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64)),
                ('extracted_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_snapshots', to='lectures.extractedpage')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='lectures.generationsourcesnapshot')),
            ],
            options={
                'ordering': ('source_snapshot', 'page_number'),
            },
        ),
        migrations.CreateModel(
            name='SlideDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slides', to='lectures.generationrequest')),
            ],
            options={
                'ordering': ('generation', 'position'),
            },
        ),
        migrations.CreateModel(
            name='SlideRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('created_by_actor_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='lectures.slidedraft')),
            ],
            options={
                'ordering': ('slide', 'version'),
            },
        ),
        migrations.AddField(
            model_name='slidedraft',
            name='approved_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_for_slides', to='lectures.sliderevision'),
        ),
        migrations.CreateModel(
            name='SlideClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='lectures.sliderevision')),
            ],
            options={
                'ordering': ('revision', 'position'),
            },
        ),
        migrations.CreateModel(
            name='NarrationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('text', models.TextField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='narration_statements', to='lectures.sliderevision')),
            ],
            options={
                'ordering': ('revision', 'position'),
            },
        ),
        migrations.CreateModel(
            name='CanonicalNarrationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64)),
                ('approved_by_actor_id', models.PositiveBigIntegerField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_narration', to='lectures.sliderevision')),
            ],
            options={
                'ordering': ('revision', 'approved_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('supported_text_sha256', models.CharField(max_length=64)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references', to='lectures.slideclaim')),
                ('narration_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references', to='lectures.narrationstatement')),
                ('page_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='lectures.generationpagesnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['requested_by', 'status'], name='generation_actor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['chapter', 'created_at'], name='generation_chapter_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='generationsourcesnapshot',
            constraint=models.UniqueConstraint(fields=('generation', 'source'), name='unique_generation_source_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='generationpagesnapshot',
            constraint=models.UniqueConstraint(fields=('source_snapshot', 'page_number'), name='unique_generation_snapshot_page'),
        ),
        migrations.AddConstraint(
            model_name='generationpagesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='generation_snapshot_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sliderevision',
            constraint=models.UniqueConstraint(fields=('slide', 'version'), name='unique_slide_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='slidedraft',
            constraint=models.UniqueConstraint(fields=('generation', 'position'), name='unique_generation_slide_position'),
        ),
        migrations.AddConstraint(
            model_name='slideclaim',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='unique_revision_claim_position'),
        ),
        migrations.AddConstraint(
            model_name='slideclaim',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='slide_claim_text_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='narrationstatement',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='unique_revision_narration_position'),
        ),
        migrations.AddConstraint(
            model_name='narrationstatement',
            constraint=models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='narration_statement_text_not_empty'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['page_snapshot', 'start_offset'], name='source_ref_page_offset_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcereference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim__isnull', False), ('narration_statement__isnull', True)), models.Q(('claim__isnull', True), ('narration_statement__isnull', False)), _connector='OR'), name='source_reference_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='sourcereference',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='source_reference_valid_offsets'),
        ),
    ]
