# Generated by Django 6.0.8 on 2026-08-11 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_generationrequest_generationsourcesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('SOURCE_CONTENT_READY', 'Source and content ready'), ('SLIDE_NARRATION_DRAFT', 'Slide and narration draft'), ('TEACHER_SLIDE_NARRATION_APPROVED', 'Teacher approved current slides and narration'), ('RECORDING_PENDING', 'Recording pending'), ('RECORDING_READY', 'Recording ready'), ('DRAFT_VIDEO_PENDING', 'Draft video pending'), ('DRAFT_VIDEO_READY', 'Draft video ready'), ('TEACHER_VIDEO_REVISION_REQUESTED', 'Teacher requested video revision'), ('TEACHER_VIDEO_APPROVED', 'Teacher approved video'), ('FINAL_ADMIN_APPROVED', 'Final administrator approval'), ('EXPORT_READY', 'Export-ready handoff')], default='SOURCE_CONTENT_READY', max_length=48)),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('slide_approval_fingerprint', models.CharField(blank=True, max_length=64)),
                ('recording_reference', models.CharField(blank=True, max_length=128)),
                ('draft_video_reference', models.CharField(blank=True, max_length=128)),
                ('export_reference', models.CharField(blank=True, max_length=128)),
                ('teacher_video_approved_by', models.CharField(blank=True, max_length=128)),
                ('teacher_video_approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_admin_approved_by', models.CharField(blank=True, max_length=128)),
                ('final_admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_workflow', to='lectures.generationrequest')),
            ],
            options={
                'ordering': ('-created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actor_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMINISTRATOR', 'Administrator'), ('SYSTEM_WORKER', 'System worker')], max_length=24)),
                ('actor_identity_reference', models.CharField(max_length=128)),
                ('previous_state', models.CharField(blank=True, choices=[('SOURCE_CONTENT_READY', 'Source and content ready'), ('SLIDE_NARRATION_DRAFT', 'Slide and narration draft'), ('TEACHER_SLIDE_NARRATION_APPROVED', 'Teacher approved current slides and narration'), ('RECORDING_PENDING', 'Recording pending'), ('RECORDING_READY', 'Recording ready'), ('DRAFT_VIDEO_PENDING', 'Draft video pending'), ('DRAFT_VIDEO_READY', 'Draft video ready'), ('TEACHER_VIDEO_REVISION_REQUESTED', 'Teacher requested video revision'), ('TEACHER_VIDEO_APPROVED', 'Teacher approved video'), ('FINAL_ADMIN_APPROVED', 'Final administrator approval'), ('EXPORT_READY', 'Export-ready handoff')], max_length=48)),
                ('new_state', models.CharField(choices=[('SOURCE_CONTENT_READY', 'Source and content ready'), ('SLIDE_NARRATION_DRAFT', 'Slide and narration draft'), ('TEACHER_SLIDE_NARRATION_APPROVED', 'Teacher approved current slides and narration'), ('RECORDING_PENDING', 'Recording pending'), ('RECORDING_READY', 'Recording ready'), ('DRAFT_VIDEO_PENDING', 'Draft video pending'), ('DRAFT_VIDEO_READY', 'Draft video ready'), ('TEACHER_VIDEO_REVISION_REQUESTED', 'Teacher requested video revision'), ('TEACHER_VIDEO_APPROVED', 'Teacher approved video'), ('FINAL_ADMIN_APPROVED', 'Final administrator approval'), ('EXPORT_READY', 'Export-ready handoff')], max_length=48)),
                ('reason_code', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('SLIDE_NARRATION_DRAFT', 'Slide and narration draft coordination'), ('RECORDING_READINESS', 'Recording readiness coordination'), ('DRAFT_VIDEO_READINESS', 'Draft-video readiness coordination'), ('EXPORT_READINESS', 'Export handoff readiness coordination')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('workflow_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Terminal failure'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_at', models.DateTimeField()),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=128)),
                ('completion_idempotency_key', models.CharField(blank=True, max_length=128)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('failure_reason_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=300)),
                ('created_by_actor_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMINISTRATOR', 'Administrator'), ('SYSTEM_WORKER', 'System worker')], max_length=24)),
                ('created_by_identity_reference', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('actor_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMINISTRATOR', 'Administrator'), ('SYSTEM_WORKER', 'System worker')], max_length=24)),
                ('actor_identity_reference', models.CharField(max_length=128)),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Terminal failure'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Terminal failure'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('reason_code', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='lectures.workflowjob')),
            ],
            options={
                'ordering': ('job', 'sequence'),
            },
        ),
        migrations.AddIndex(
            model_name='lectureworkflow',
            index=models.Index(fields=['state', 'updated_at'], name='workflow_state_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureworkflow',
            index=models.Index(fields=['generation', 'version'], name='workflow_generation_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='lectureworkflow',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_version_positive'),
        ),
        migrations.AddIndex(
            model_name='workflowauditevent',
            index=models.Index(fields=['workflow', 'occurred_at'], name='workflow_audit_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowauditevent',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='workflow_audit_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='workflowauditevent',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='unique_workflow_audit_sequence'),
        ),
        migrations.AddConstraint(
            model_name='workflowauditevent',
            constraint=models.UniqueConstraint(fields=('workflow', 'idempotency_key'), name='unique_workflow_transition_key'),
        ),
        migrations.AddIndex(
            model_name='workflowjob',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='workflow_job_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowjob',
            index=models.Index(fields=['leased_until', 'status'], name='workflow_job_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.CheckConstraint(condition=models.Q(('workflow_version__gte', 1)), name='workflow_job_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.UniqueConstraint(fields=('workflow', 'job_type', 'idempotency_key'), name='unique_workflow_job_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 5)), name='workflow_job_retry_bounds'),
        ),
        migrations.AddConstraint(
            model_name='workflowjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0), ('attempts__lte', models.F('max_attempts'))), name='workflow_job_attempt_bounds'),
        ),
        migrations.AddIndex(
            model_name='workflowjobevent',
            index=models.Index(fields=['job', 'occurred_at'], name='workflow_job_event_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowjobevent',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='workflow_job_event_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='workflowjobevent',
            constraint=models.UniqueConstraint(fields=('job', 'sequence'), name='unique_workflow_job_event_sequence'),
        ),
    ]
