# Generated by Django 6.0.8 on 2026-08-15 06:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_workflow_queue_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('slide_approval_fingerprint', models.CharField(max_length=64)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_completions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_completions', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'completed_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RecordingSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('selected_at', models.DateTimeField(auto_now=True)),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_selections', to=settings.AUTH_USER_MODEL)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_selections', to='lectures.slidedraft')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_selections', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'slide__position'),
            },
        ),
        migrations.CreateModel(
            name='RecordingTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=8)),
                ('media_type', models.CharField(max_length=40)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_narration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_takes', to='lectures.canonicalnarrationsnapshot')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_takes', to=settings.AUTH_USER_MODEL)),
                ('slide_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_takes', to='lectures.sliderevision')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_takes', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'slide_revision__slide', 'take_number'),
            },
        ),
        migrations.CreateModel(
            name='RecordingSelectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_selection_events', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='lectures.recordingselection')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_events', to='lectures.recordingtake')),
            ],
            options={
                'ordering': ('selection', 'version'),
            },
        ),
        migrations.AddField(
            model_name='recordingselection',
            name='current_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_selections', to='lectures.recordingtake'),
        ),
        migrations.CreateModel(
            name='RecordingCompletionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='lectures.recordingcompletion')),
                ('slide_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording_completion_items', to='lectures.sliderevision')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_items', to='lectures.recordingtake')),
            ],
            options={
                'ordering': ('completion', 'position'),
            },
        ),
        migrations.AddIndex(
            model_name='recordingtake',
            index=models.Index(fields=['workflow', 'slide_revision'], name='recording_workflow_slide_idx'),
        ),
        migrations.AddIndex(
            model_name='recordingtake',
            index=models.Index(fields=['recorded_by', 'created_at'], name='recording_teacher_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordingtake',
            constraint=models.UniqueConstraint(fields=('workflow', 'slide_revision', 'take_number'), name='unique_recording_take_number'),
        ),
        migrations.AddConstraint(
            model_name='recordingtake',
            constraint=models.CheckConstraint(condition=models.Q(('take_number__gte', 1)), name='recording_take_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingtake',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 1)), name='recording_take_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingtake',
            constraint=models.CheckConstraint(condition=models.Q(('duration_ms__gte', 1)), name='recording_take_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingselectionevent',
            constraint=models.UniqueConstraint(fields=('selection', 'version'), name='unique_recording_selection_event_version'),
        ),
        migrations.AddConstraint(
            model_name='recordingselectionevent',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='recording_selection_event_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingselection',
            constraint=models.UniqueConstraint(fields=('workflow', 'slide'), name='unique_recording_selection'),
        ),
        migrations.AddConstraint(
            model_name='recordingselection',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='recording_selection_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='recordingcompletionitem',
            constraint=models.UniqueConstraint(fields=('completion', 'position'), name='unique_recording_completion_position'),
        ),
        migrations.AddConstraint(
            model_name='recordingcompletionitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='recording_completion_position_positive'),
        ),
    ]
