# Generated by Django 6.0.8 on 2026-08-20 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_teacher_recording_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherVideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revision requested')], max_length=24)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_video_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminFinalVideoApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_final_video_approvals', to=settings.AUTH_USER_MODEL)),
                ('teacher_review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin_final_approval', to='lectures.teachervideoreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoEditDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('BRANDING', 'Institutional branding'), ('CAPTION_LAYOUT', 'Caption layout'), ('TRANSITION_TIMING', 'Transition timing'), ('SPOKEN_CONTENT_REMOVAL', 'Approved spoken-content removal')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_edit_decisions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_edit_decisions', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SpokenContentEditApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spoken_content_edit_approvals', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spoken_approval', to='lectures.videoeditdecision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoRenderInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('slide_approval_fingerprint', models.CharField(max_length=64)),
                ('recording_reference', models.CharField(max_length=128)),
                ('input_sha256', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_inputs', to=settings.AUTH_USER_MODEL)),
                ('recording_completion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_inputs', to='lectures.recordingcompletion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_inputs', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='VideoRenderInputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title_snapshot', models.CharField(max_length=200)),
                ('claims_snapshot', models.JSONField(default=list)),
                ('narration_snapshot', models.TextField()),
                ('narration_sha256', models.CharField(max_length=64)),
                ('take_sha256', models.CharField(max_length=64)),
                ('take_duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('take_storage_key', models.CharField(max_length=255)),
                ('canonical_narration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_input_items', to='lectures.canonicalnarrationsnapshot')),
                ('render_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='lectures.videorenderinput')),
                ('slide_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_input_items', to='lectures.sliderevision')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_input_items', to='lectures.recordingtake')),
            ],
            options={
                'ordering': ('render_input', 'position'),
            },
        ),
        migrations.CreateModel(
            name='VideoRenderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending local render'), ('RUNNING', 'Local render running'), ('SUCCEEDED', 'Draft render available'), ('FAILED', 'Local render failed'), ('STALE', 'Inputs are stale')], default='PENDING', max_length=16)),
                ('manifest_storage_key', models.CharField(max_length=255)),
                ('video_storage_key', models.CharField(max_length=255)),
                ('video_sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('failure_reason_code', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='lectures.videorenderversion')),
                ('render_input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='render_versions', to='lectures.videorenderinput')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_versions', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'version'),
            },
        ),
        migrations.CreateModel(
            name='VideoRenderAppliedEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_to_renders', to='lectures.videoeditdecision')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_edits', to='lectures.videorenderversion')),
            ],
            options={
                'ordering': ('render', 'position'),
            },
        ),
        migrations.CreateModel(
            name='VideoRenderRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('failed_render', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery', to='lectures.videorenderversion')),
                ('replacement_render', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_origin', to='lectures.videorenderversion')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_recoveries', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_render_recoveries', to='lectures.lectureworkflow')),
            ],
            options={
                'ordering': ('workflow', 'requested_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='VideoExportPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('storage_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending local package'), ('RUNNING', 'Local package running'), ('READY', 'Local package ready'), ('FAILED', 'Local package failed'), ('STALE', 'Approval or inputs are stale')], default='PENDING', max_length=16)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('failure_reason_code', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='export_package', to='lectures.adminfinalvideoapproval')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video_export_package', to='lectures.workflowjob')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_export_packages', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_export_packages', to='lectures.lectureworkflow')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_packages', to='lectures.videorenderversion')),
            ],
            options={
                'ordering': ('workflow', 'version'),
            },
        ),
        migrations.AddField(
            model_name='videoeditdecision',
            name='base_render',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_decisions', to='lectures.videorenderversion'),
        ),
        migrations.AddField(
            model_name='teachervideoreview',
            name='render',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_review', to='lectures.videorenderversion'),
        ),
        migrations.AddField(
            model_name='adminfinalvideoapproval',
            name='render',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admin_final_approval', to='lectures.videorenderversion'),
        ),
        migrations.CreateModel(
            name='VideoReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='video_review_submission', to='lectures.workflowjob')),
                ('render', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_submission', to='lectures.videorenderversion')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_review_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='videorenderinput',
            index=models.Index(fields=['workflow', 'created_at'], name='video_input_workflow_idx'),
        ),
        migrations.AddConstraint(
            model_name='videorenderinputitem',
            constraint=models.UniqueConstraint(fields=('render_input', 'position'), name='unique_video_input_position'),
        ),
        migrations.AddConstraint(
            model_name='videorenderinputitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='video_input_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='videorenderinputitem',
            constraint=models.CheckConstraint(condition=models.Q(('take_duration_ms__gte', 1)), name='video_input_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='videorenderversion',
            index=models.Index(fields=['status', 'requested_at'], name='video_render_status_idx'),
        ),
        migrations.AddIndex(
            model_name='videorenderversion',
            index=models.Index(fields=['workflow', 'version'], name='video_render_workflow_idx'),
        ),
        migrations.AddConstraint(
            model_name='videorenderversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='unique_video_render_version'),
        ),
        migrations.AddConstraint(
            model_name='videorenderversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='video_render_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='videorenderappliededit',
            constraint=models.UniqueConstraint(fields=('render', 'decision'), name='unique_render_edit'),
        ),
        migrations.AddConstraint(
            model_name='videorenderappliededit',
            constraint=models.UniqueConstraint(fields=('render', 'position'), name='unique_render_edit_position'),
        ),
        migrations.AddIndex(
            model_name='videoexportpackage',
            index=models.Index(fields=['status', 'requested_at'], name='video_export_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoexportpackage',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='unique_video_export_version'),
        ),
        migrations.AddConstraint(
            model_name='videoexportpackage',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='video_export_version_positive'),
        ),
        migrations.AddIndex(
            model_name='videoeditdecision',
            index=models.Index(fields=['workflow', 'created_at'], name='video_edit_workflow_idx'),
        ),
    ]
