# Generated by Codex for render failure diagnostics.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0008_remotion_video_assembly"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorenderversion",
            name="failure_detail",
            field=models.TextField(blank=True),
        ),
    ]
