# Generated by Django 6.0.8 on 2026-09-16 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_videorenderversion_failure_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='pptx_storage_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='LectureDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecture_divisions', to='lectures.chapter')),
            ],
            options={
                'ordering': ('chapter', 'number'),
            },
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='lectures.lecturedivision'),
        ),
        migrations.AddIndex(
            model_name='lecturedivision',
            index=models.Index(fields=['chapter', 'number'], name='lecture_division_chapter_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturedivision',
            constraint=models.UniqueConstraint(fields=('chapter', 'number'), name='unique_lecture_division_number'),
        ),
        migrations.AddConstraint(
            model_name='lecturedivision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='lecture_division_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='lecturedivision',
            constraint=models.CheckConstraint(condition=models.Q(('page_start__isnull', True), ('page_end__isnull', True), ('page_end__gte', models.F('page_start')), _connector='OR'), name='lecture_division_page_range_ordered'),
        ),
    ]
