# Generated by Django 6.0.8 on 2026-10-01 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_generationrequest_pptx_storage_key_lecturedivision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherlessRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Queued for local render'), ('RUNNING', 'Local render running'), ('SUCCEEDED', 'Teacherless lecture available'), ('FAILED', 'Local render failed')], default='PENDING', max_length=16)),
                ('manifest_relative_path', models.CharField(blank=True, max_length=255)),
                ('video_relative_path', models.CharField(blank=True, max_length=255)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('video_sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scene_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('failure_reason_code', models.CharField(blank=True, max_length=64)),
                ('failure_detail', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherless_renders', to='lectures.generationrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherless_renders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('generation', 'version'),
                'indexes': [models.Index(fields=['status', 'requested_at'], name='teacherless_render_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('generation', 'version'), name='unique_teacherless_render_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='teacherless_render_version_positive')],
            },
        ),
    ]
